[tox]
envlist =
    py{311,312,313,314}-test
    linkcheck
    codestyle
    securityaudit
requires =
    setuptools
    pip
isolated_build = true

[testenv]
# Suppress display of matplotlib plots generated during docs build, if any
setenv =
    MPLBACKEND=agg

# Pass through the following environment variables which may be needed for the CI
passenv = HOME, WINDIR,LC_ALL, LC_CTYPE, CC, CI

# Run the tests in a temporary directory to make sure that we don't import
# this package from the source tree
changedir = .tmp/{envname}

# tox environments are constructed with so-called 'factors' (or terms)
# separated by hyphens, e.g. test-devdeps-cov. Lines below starting with factor:
# will only take effect if that factor is included in the environment name. To
# see a list of example environments that can be run, along with a description,
# run:
#
#     tox -l -v
#
description =
    run tests

# The following provides some specific pinnings for key packages
#deps =

# The following indicates which extras_require from setup.cfg will be installed
extras =
    test

commands =
    pip freeze

[testenv:codestyle]
skip_install = true
changedir = .
description = code style audit with ruff
deps = ruff
commands = ruff check

[testenv:securityaudit]
skip_install = true
changedir = .
description = security audit with bandit
deps = bandit
commands = bandit -r peaker -c .bandit.yaml
