name: tests

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
  push:
    branches:
      - main
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  supported-pythons:
    runs-on: ubuntu-latest
    steps:
      - id: supported-pythons
        uses: zacharyburnett/supported-pythons@2.0.1
        with:
          package: "x${{ inputs.git_repository }}x"
          package-ref: "x${{ inputs.git_ref }}x"
    outputs:
      versions: ${{ steps.supported-pythons.outputs.versions }}
  test:
    needs:
      - supported-pythons
    strategy:
      fail-fast: false
      matrix:
        runs-on: ["ubuntu-latest"]
        python-version: ${{ fromJSON(needs.supported-pythons.outputs.versions) }}
        coverage: [false]
        include:
          - runs-on: "ubuntu-latest"
            python-version: "3"
            coverage: true
          - runs-on: "macos-latest"
            python-version: "3"
    name: run tests (Python ${{matrix.python-version}}, ${{ matrix.runs-on }})
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install ".[test]" ${{ matrix.coverage && 'coverage pytest-cov' || '' }}
      - run: pytest ${{ matrix.coverage && '--cov' || '' }}
      - if: matrix.coverage
        name: report coverage to summary
        run: |
          coverage combine
          echo '## Coverage Report' >> $GITHUB_STEP_SUMMARY
          coverage report -i -m --format=markdown | tee -a $GITHUB_STEP_SUMMARY
